server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atspring
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB53Dialect