server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atSpring
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect